version: '3.8'

services:
  web:
    build: .
    restart: always
    ports:
      - "5000:5000"
    environment:
      - DB_HOST=db  # <-- Esto es clave para que no busque 'localhost'
    depends_on:
      - db

  db:
    image: mariadb:10.6
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root_password_seguro
      MYSQL_DATABASE: aula_cisco
      MYSQL_USER: cisco_admin
      MYSQL_PASSWORD: holahola
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: